---
- name: Listen for events on a webhook
  hosts: all

  sources:
   - ansible.eda.webhook:
       host: 0.0.0.0
       port: 5000

  rules:
   - name: Handle message payload
     condition: event.meta.headers is defined

     action:
       debug:
         msg: "Received: {{ event }}"
     
     labels:
      - 'Activated by Red Hat Insights'
      - {{ event.payload.application }}
      - {{ event.payload.event_type }}
      - {{ event.payload.context.display_name | default('Activated by Red Hat Insights') }}
